# Generated by Django 5.0.3 on 2024-12-16 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lease',
            new_name='LeaseContract',
        ),
        migrations.AddField(
            model_name='unit',
            name='status',
            field=models.CharField(choices=[('available', 'متوفر'), ('accupied', 'مشغولة')], default='available', max_length=20, verbose_name='الحالة'),
        ),
    ]
