# Generated by Django 5.0.3 on 2024-12-16 06:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_rename_lease_leasecontract_unit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leasecontract',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leasecontract',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AddConstraint(
            model_name='leasecontract',
            constraint=models.CheckConstraint(check=models.Q(('end_date__gte', models.F('start_date'))), name='valid_contract_dates'),
        ),
    ]
