# Generated by Django 5.0.3 on 2024-12-16 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_leasecontract_created_at_leasecontract_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leasecontract',
            name='is_cancelled',
            field=models.BooleanField(default=False, verbose_name='ملغى'),
        ),
        migrations.AddField(
            model_name='leasecontract',
            name='notification_sent',
            field=models.BooleanField(default=False, verbose_name='تم ارسال التنبيه'),
        ),
        migrations.AddField(
            model_name='unit',
            name='description',
            field=models.TextField(blank=True, verbose_name='وصف الوحدة'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['unit_number'], name='unit_number_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['status'], name='status_idx'),
        ),
    ]
