# Generated by Django 5.0.3 on 2024-12-30 19:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_leasecontract_is_cancelled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date', models.DateField(auto_now_add=True, verbose_name='تاريخ الفاتورة')),
                ('due_date', models.DateField(verbose_name='تاريخ الاستحقاق')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ المستحق')),
                ('status', models.CharField(choices=[('pending', 'معلقة'), ('paid', 'مدفوعة'), ('overdue', 'متأخرة')], default='pending', max_length=20, verbose_name='الحالة')),
            ],
            options={
                'verbose_name': 'فاتورة',
                'verbose_name_plural': 'الفواتير',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(auto_now_add=True, verbose_name='تاريخ الدفع')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ المدفوع')),
                ('payment_method', models.CharField(choices=[('credit_card', 'بطاقة الائتمان'), ('bank_transfer', 'تحويل بنكي')], max_length=50, verbose_name='طريقة الدفع')),
            ],
            options={
                'verbose_name': 'دفعة',
                'verbose_name_plural': 'الدفعات',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم العقار')),
                ('property_type', models.CharField(choices=[('apartment', 'شقة'), ('office', 'مكتب'), ('shop', 'محل')], default='available', max_length=20, verbose_name='الحالة')),
                ('status', models.CharField(choices=[('available', 'متوفر'), ('rented', 'مؤجرة'), ('maintenance', 'تحت الصيانة')], default='available', max_length=20, verbose_name='الحالة')),
                ('address', models.TextField(verbose_name='عنوان العقار')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف العقار')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'عقار',
                'verbose_name_plural': 'العقارات',
            },
        ),
        migrations.CreateModel(
            name='RentalContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='تاريخ البدء')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الايجار الشهري')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'عقد الايجار',
                'verbose_name_plural': 'عقود الإيجار',
            },
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='leasecontract',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='leasecontract',
            name='unit',
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='unit',
            name='unit_number_idx',
        ),
        migrations.RemoveIndex(
            model_name='unit',
            name='status_idx',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='description',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='electricity_account',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='rent_price',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='status',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='unit_number',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='unit_type',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='water_account',
        ),
        migrations.AddField(
            model_name='tenant',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='عنوان'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='commercial_registration_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم التسجيل التجاري'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاريخ الإضافة'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenant',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='rentals.invoice', verbose_name='الفاتورة'),
        ),
        migrations.AddField(
            model_name='property',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AddField(
            model_name='rentalcontract',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='rentals.tenant', verbose_name='المستأجر'),
        ),
        migrations.AddField(
            model_name='rentalcontract',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='rentals.unit', verbose_name='العقار'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='rentals.rentalcontract', verbose_name='عقد الإيجار'),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='LeaseContract',
        ),
    ]
