# Generated by Django 5.0.3 on 2024-12-30 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0005_invoice_payment_property_rentalcontract_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalcontract',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='rentals.property', verbose_name='العقار'),
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
