# Generated by Django 5.0.3 on 2024-12-31 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0006_alter_rentalcontract_unit_delete_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان الطلب')),
                ('description', models.TextField(verbose_name='وصف المشكلة')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('is_progres', 'قيد التنفيذ'), ('completed', 'مكتمل')], default='pending', max_length=20, verbose_name='الحالة')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='rentals.property', verbose_name='الوحدة')),
            ],
            options={
                'verbose_name': 'طلب الصيانة',
                'verbose_name_plural': 'طلبات الصيانة',
            },
        ),
    ]
